# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# first.py
# Created on: 2014-12-18 09:02:57.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
from arcpy.sa import *
env.workspace = "D:\\Users\\mduvall\\Zocalo\\InterpScript\\script2.mdb"
env.overwriteOutput = True
arcpy.CheckOutExtension("Spatial")

# Local variables:
c_density = "D:\\Users\\mduvall\\Zocalo\\InterpScript\\InterpData.mdb\\c_density"
marsh = "D:\\Users\\mduvall\\Zocalo\\InterpScript\\marsh_area_good.shp"
arcpy.env.extent = marsh
cellSize = 10.0
fieldList = arcpy.ListFields(c_density, "F*")

for field in fieldList:
     
    #interpolate IDW
    tempIdw = Idw(c_density, field.name, cellSize, 2)

    #interpolate Kriging
    tempKrig = Kriging(c_density, field.name, "Spherical", cellSize, field.name + "pred")

    #clip
    tIDWMarsh = ExtractByMask(tempIdw, marsh)
    tKrigMarsh = ExtractByMask(tempKrig, marsh)

    #times 10,000,000
    tIDWtimes = Times(tIDWMarsh, 10000000)
    tKrigTimes = Times(tKrigMarsh, 10000000)

    #export table
    Sample(tIDWtimes, tKrigTimes, field.name + "idw", "NEAREST")
    Sample(tKrigTimes, tIDWtimes, field.name + "krig", "NEAREST")

    #save rasters
    tIDWtimes.save("final_" + field.name + "_idw")
    tKrigTimes.save("final_" + field.name + "_krig")

    
